### ISSUE TITLE
It doesn't do anything

### ISSUE THREAD

**Issue by cedricdhaese** [maksimKorzh/opencv-chess-bot#2]
![image](https://user-images.githubusercontent.com/67026186/210186096-56cc9a53-9be3-489b-9fd6-e6b8ff51f8be.png)
So Ik eep getting that whenever I run the program nothing happens and it just ends the process, all files are in the right directory tho

**Comment by maksimKorzh** [comment]
You're on windows, I can't help

**Comment by winapiadmin** [comment]
After replacing bbc and Stockfish to compatible version for Windows (only Stockfish) and default values, this is the exception:
`Could not locate the image (highest confidence = 0.598)`
